# Generated by Django 3.0.6 on 2020-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='overtime',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
