# Generated by Django 3.0.6 on 2020-06-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='sender',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='worker',
            new_name='employee',
        ),
    ]
