# Generated by Django 3.0.6 on 2020-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='overtime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
