# Generated by Django 3.0.6 on 2020-06-01 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20200601_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='Overview',
        ),
    ]
